# Generated by Django 4.2.20 on 2025-04-30 07:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoundModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.gamemodel')),
            ],
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_player1', to='score.playermodel'),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_player2', to='score.playermodel'),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='player3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_player3', to='score.playermodel'),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='player4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_player4', to='score.playermodel'),
        ),
        migrations.CreateModel(
            name='ScoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.playermodel')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.roundmodel')),
            ],
            options={
                'unique_together': {('round', 'player')},
            },
        ),
    ]
