# Generated by Django 4.2.20 on 2025-04-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uma_2', models.IntegerField(default=10, verbose_name='2位のウマ')),
                ('uma_3', models.IntegerField(default=-10, verbose_name='3位のウマ')),
                ('uma_4', models.IntegerField(default=-30, verbose_name='4位のウマ')),
                ('return_score', models.IntegerField(default=30000, verbose_name='返し点')),
                ('rounding_rule', models.CharField(choices=[('round', '四捨五入'), ('floor', '切り捨て（5捨6入）'), ('ceil', '切り上げ')], default='floor', max_length=10, verbose_name='丸め処理方法')),
                ('tie_rule', models.CharField(choices=[('split', '均等分配（同着者でウマを割る）'), ('prefer_early', '順位順（早く登録された人に全部与える）')], default='split', max_length=15, verbose_name='同着ウマ処理方法')),
            ],
        ),
        migrations.AddField(
            model_name='scoremodel',
            name='raw_score',
            field=models.IntegerField(default=25000, verbose_name='素点'),
        ),
        migrations.AlterField(
            model_name='scoremodel',
            name='point',
            field=models.FloatField(blank=True, null=True, verbose_name='ポイント'),
        ),
    ]
