# Generated by Django 4.2.20 on 2025-04-30 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_gamesettingmodel_scoremodel_raw_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='score.gamesettingmodel', verbose_name='適用する設定'),
        ),
    ]
