# Generated by Django 4.2.20 on 2025-04-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_gamemodel_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundmodel',
            name='override_tie_rule',
            field=models.CharField(blank=True, choices=[('', 'ゲーム設定に従う'), ('split', '均等分配'), ('prefer_early', '順位順（早い人優先）')], default='', max_length=15, verbose_name='この対局での同着処理'),
        ),
    ]
