# Generated by Django 4.2.20 on 2025-04-30 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0006_gamesettingmodel_unique_game_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesettingmodel',
            name='name',
        ),
    ]
